matrix:
  fast_finish: true

environment:
  matrix:
    - PYTHON_VERSION: "3.8"
      MINICONDA: C:\Miniconda36-x64

build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Cancel older builds for the same PR
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Set up environment
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - conda env create -f environment.yml
  - activate earthpy-dev
  - pip install -e . --no-deps
  - pip install -r requirements-dev.txt

test_script:
  - conda list
  - pytest
