version: 2
formats: []
python:
   version: 3.8
   install:
      - requirements: requirements-dev.txt
      - method: pip
        path: .
sphinx:
  # fail_on_warning: true
  configuration: docs/conf.py
