language: python
python:
- 3.8
install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/test.sh
- "./.travis/test.sh"
env:
  global:
  - secure: ctpB/JzRnXICQMr2FdbB48eyZXTLMPpfRLjqumBtgTL1rZ3dPYF5zxVahv9E1noNpRplyGEZBAecGGtsNN2+AGDavvvwNtE8wUHHcGkjnQ0N5J0J3Df/n3P+nes9SPvzq5GR8EWHtAKm1J/4iuBZQf6zZEoeyAIqTcgW+P/sA4iKfQjaUROMXODL9nuVXTlT3qonCiQKiZZaTVxPpS6OZd3ydlKvmLEZDI5GoOuZJopdoVJ7feI2oud1zlKMVSgzABSWE19lZcq7TztQ2CwQcK/VYKY0x3IP7lJU+LApVjCFzTqYe3GIjVOiTDEq6Yy/gs9CE0NQ4khNjK+7t2Bm7QFjJnOTzAHVvlisx0arNo6U2BoB2+QlZu4nvAO6leWXpHo2VdeIz5WimbT3vfqgpsNGd5CQMa7pH9L7zv3S3SEFh3BHbXetMrhKd0Vc4BUQs+ZoCfmg3rLMAQyrbzfl4l2z99aWxqC/gII0S63CglMyNySp8YveICJnylIdJrdE0nd4qnH6DCkowqqEQv4jijY/mE6hZupwh+By0NbsK6MlGMecC6N7OW2O116WZR0+THTFAorQel72NJEkWAK9mFWnEP6hlcmuqmPGlNj6wMAZ3IgYup65tSbfS8yv9XepOTXc70cyxHA1+HYfN8t0DkCVv7TbLiAgJr+aPXcKMjw=
dd:
  secure: XS6EgwgI/csncGchz3Tgv2LItXT0ymDB/n4X87KjiXPFyyXlIFx9mMzMNHYOR580nbhgBtEDEV7YSDwxIU3jCarkKSoA0wlfImW3h0ov5YW36VXCjmZnddD5mFOJxAJWb/XcpTzpSaa7kG4qUNsGvXZ1i26YUUJfxslM3FucoRz4VcH5+wMuB8kxU86VCg4fFYiv3iCUTELRbZFpq+bHvhG+itoghwFoQ5CJFpzjNccey0Fr8uOx9inLno4TkSU6rWuxityTWY+b3yHhlgGBdp+PnsNiRUVxw3zHtOKqBETuk6m7Xan4qKb+FvZRRMx816coYDuiaDIIz7zNO6NeHdEUkfLc7gJshG5368foLxrcGxk5e/xR51+/IcFxK/zhlnH5b5W6AR2PtZ9ycYIiXd70O6lMeZNUtrp5z/fSfUN2vlnZYqSC8WpglXkcNP1jeKI0tZflaWFm6wKrZvgJGG9d496jfhmRpHxOobARn4XOsus321sAjifPDVhtIu8AvcACRy7l9iR2KJVPUO47BOJ8aaZC7Yx8sltfaTtLj0VgRT38u85/7FamFi/qd1VThoYEJbE68TAmwM525z4Us8pxiNEhhUlrKy6Xa0SAU+RQRLxbX9cMOKIz5iphrDmKpmQzyyaeELHroxBUm2ltloSvPDFiD2p1VpAMSdQBtoc=
