# For testing build?

channels:
    - conda-forge
    - defaults

dependencies:
    - pip
    - bumpversion
    - pre-commit
    - wheel
    - watchdog
    - flake8
    - tox
    - coverage
    - Sphinx
    - twine
    - pytest
    - pytest-runner
    - pytest-cov
