name: awhere-python

channels:
  - conda-forge
  - defaults

dependencies:
  # Base dependencies
  - python=3.8
  - pip

  # Core scientific python
  - matplotlib
  - numpy
  - seaborn

  # Spatial packages
  - geopandas
  - earthpy
  - shapely
  - rasterstats
  - descartes
  - rtree
