name: awherepy-docs

channels:
  - conda-forge

dependencies:
  # Base dependencies
  - python=3.8

  # Core scientific python
  - matplotlib
  - numpy
  - seaborn

  # Spatial packages
  - geopandas
  - earthpy
  - shapely
  - rasterstats
  - descartes
  - rtree

  # Documentation
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
